### ISSUE TITLE
V4.1.2 limits max current selection

### ISSUE THREAD

**Issue by mikebaz** [OpenEVSE/ESP32_WiFi_V4.x#326]
I just downgraded from 4.1.2 to 4.1.1 because somehow, the power dropdown decided to limit itself to 15A as a maximum.  Before doing the update, the power was set to 15A for an overnight charge session, but then I did the update and that was the highest I could go.

**Comment by glynhudson** [comment]
Does it still limit to 15A when charging level: L2 is selected?

On Wed, 9 Mar 2022 at 13:39, mikebaz ***@***.***> wrote:
>
> I just downgraded from 4.1.2 to 4.1.1 because somehow, the power dropdown decided to limit itself to 15A as a maximum. Before doing the update, the power was set to 15A for an overnight charge session, but then I did the update and that was the highest I could go.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
Glyn Hudson

https://openenergymonitor.org
http://zerocarbonadventures.co.uk

**Comment by mikebaz** [comment]
Yes - I even tried changing from L2 (which is where I normally have it) to L1 (which changed the limit to 12A), then back to L2 (which changed the limit back to 15A).

**Comment by chris1howell** [comment]
I can verify this. The maximum in the list is whatever the station is set to. In my case the minimum was 6 and the maximum was 24.

**Comment by jeremypoulter** [comment]
I did have a look at this, can you check the RAPI page and see what values are being sent from the controller? I think they are being set in the flash in the EVSE, but this then can't be reverted after the first setting. I need to check, as I thought I was setting them as volatile....

**Comment by Tifaifai** [comment]
> 
idem with 28A

**Comment by chris1howell** [comment]
Looks fine in RAPI.

No trouble setting higher current
> $SC 40
< $OK 40^04

Min and Max look fine.
> $GC
< $OK 6 80 40 40^1E

/config looks strange
..."max_current_soft":24,"min_current_hard":6,"max_current_hard":24,... 
Have not seen Max hard and soft before.

**Comment by shadowmite** [comment]
I see the same issue, was set to 24a before update and now I can’t set it higher.

**Comment by glynhudson** [comment]
Interesting, my current was set to 32A before the upgrade and is still showing 32A option now. 

For anyone effected by this, a workaround is to issue RAPI command `$SC 32`. This can be done via the web interface if you enable 'advanced' and 'developer toggles. 

![Screenshot 2022-03-10 00 38 05](https://user-images.githubusercontent.com/758844/157563794-d82971f6-5a8c-4623-954b-8586b3c0f8e8.png)

**Comment by mikebaz** [comment]
thank you all for the fast replies, confirmation, and correction to the more accurate details, as well as the workaround.  I've gone back up to 4.1.2 knowing I can work around this for now. 🙂

**Comment by jeremypoulter** [comment]
I think I understand what the issue is, the `$SC` command does not operate quite as documented:

https://github.com/lincomatic/open_evse/blob/development/firmware/open_evse/rapi_proc.h#L183-L188
does not match the code
https://github.com/lincomatic/open_evse/blob/development/firmware/open_evse/rapi_proc.cpp#L456-L459

And also I think I miss-understood when the `M` option was supposed to be for anyway, but anyway we use the value saved in the EEPROM, exposed as `max_current_hard`, as the maximum current then manage it via setting the volatile settings. This would work fine for fresh OpenEVSE units that have only been used with the v4.1.2 firmware (which is essentially what I did the work with as I was constantly swapping between the US and EU firmware) but existing units that happened to have had a current configured would fail with this issue. 

Hopefully won't be too much of a problem to resolve the issue.

**Comment by sspearing** [comment]
My EVSE was set to 22 A when upgraded and per the above comments that became the new max in the drop down on the webUI.  Using RAPI, I set it back to 32 A.  (SC:   $OK 6 80 32 32^1E)

I just wanted to draw you attention to the pilot readout in the image below.  This may be part of what you found already.
![image](https://user-images.githubusercontent.com/73603968/158044145-f56992e2-7770-481e-a0ad-0453dd3831b2.png)
