### ISSUE TITLE
How to BUY the OpenEVSE right now?

### ISSUE THREAD

**Issue by slavkobrzeg** [OpenEVSE/ESP32_WiFi_V4.x#383]
I'm so sorry guys, but I don't know where to ask and get some answer. I sent an email to Chris directly, but...

So does anybody know when/where i can buy one OpenEVSE kit? I do have one bought a couple years ago and I need another one. I can buy it in the UK or the US whatever.

Thanks in advance for any answer.

**Comment by glynhudson** [comment]
We sell them in the UK: https://shop.openenergymonitor.com/openevse-wifi-ev-charging-station-7kw-european-kit/
and Chris sells them in the USA: https://store.openevse.com/

However, due to the global semiconductor shortage we're struggling to obtain parts so stock levels are low at the moment. We will have stock of a few EmonEVSE units in a couple of weeks. I'm afraid we don't have an ETA for kits, but it looking like 3-4 weeks.
