### ISSUE TITLE
Allow charging control to 1A

### ISSUE THREAD

**Issue by andriuskr** [OpenEVSE/ESP32_WiFi_V4.x#458]
Now Tesla through its API alows to set minimum charging rate to 1A. Why not allow it to OpenEVSE. Would be very usefull for Solar only charging.
![image](https://user-images.githubusercontent.com/13429780/198269313-130256d9-d6b6-4ed6-a14f-b536d33ee57d.png)

**Comment by chris1howell** [comment]
The minimum value defined in the J1772 spec is 6A. It is not possible to
send a lower value with the pilot signal.

**Comment by andriuskr** [comment]
> The minimum value defined in the J1772 spec is 6A. It is not possible to send a lower value with the pilot signal.
> […](#)
Is it the same for 3 phase Type-2 mennekes ?

**Comment by glynhudson** [comment]
>Is it the same for 3 phase Type-2 mennekes ?

Yes

**Comment by glynhudson** [comment]
It's very cool that Tesla allows charging down to 1A, I wonder what the efficiency is at this low level? Probably quite poor, but I guess if it's coming from solar it doest matter too much. To control the current less than 6A we would need to interface directly with the Tesla API this would not work very well for solar PV divert since there is quite a delay between an API request and the change in current being applied.
