### ISSUE TITLE
Restarting controller via HTTP throws error 500

### ISSUE THREAD

**Issue by ruimarinho** [OpenEVSE/ESP32_WiFi_V4.x#479]
Hi,

I'm on 4.1.6-dev and attempting to restart the controller via HTTP (using the UI or simply doing a curl to `https://openevse/r?json=1&rapi=$FR`) results in an error 500 with response `{"cmd":"$FR","error":"RAPI_RESPONSE_TIMEOUT"}`.

Interestingly the HTTP request is working because looking at the controller's terminal I see `$FR^30` followed by the asynchronous boot command `$AB`.

**Comment by glynhudson** [comment]
I'm able to replicate this issue, but it does not seem to be caused a problem since the controller still restarts. But I agree it would be good to not have the error. 

![Screenshot 2023-03-31 02 01 48](https://user-images.githubusercontent.com/758844/228996855-5d0dcb25-8cb1-4bae-81d6-b56b9e55e653.png)

**Comment by KipK** [comment]
This will be solved by PR #595 commit https://github.com/OpenEVSE/ESP32_WiFi_V4.x/pull/618/commits/c1d93a1b42739797592a8dacacdddee9f1b44aca
