### ISSUE TITLE
RAPI codes $FE and $FD no longer work in 4.2.2

### ISSUE THREAD

**Issue by omriasta** [OpenEVSE/ESP32_WiFi_V4.x#604]
I usually use these codes through mqtt but I have tried sending them in the user interface in the developer panel as well. The codes register, I get an OK response in the web interface. It appears to change the status or do something but then immediately goes back.
I have tried this under both the old and new web ui. Downgrading to 4.1.7 fixes this issue. Though staying at 4.1.7 and upgrading just the new web ui also breaks this.

**Comment by jeremypoulter** [comment]
This is expected behaviour. The latest version is now more forceful in making sure the EVSE is in the state that WiFi firmware expects. With the v4.2.2 release the HTTP API should implement all the functions of RAPI (and more) so we made the decision to make that change. Also note using RAPI has been deprecated since the v4 release.

**Comment by omriasta** [comment]
Understood, is there an option to enable/disable using mqtt?

**Comment by KipK** [comment]
use the claims or override endpoint on mqtt:

https://openevse.stoplight.io/docs/openevse-wifi-v4/c03364fd24abd-mqtt

**Comment by omriasta** [comment]
Got it, thank you!!
