### ISSUE TITLE
OCPP does not set `max_current`

### ISSUE THREAD

**Issue by imle** [OpenEVSE/ESP32_WiFi_V4.x#632]
So far as I can tell, this is not being sent to OCPP. In home assistant I am getting the default value of 32A.

**Comment by jeremypoulter** [comment]
Please can you give more details of your setup? Which OCPP server are you connecting to what home assistant plug in, what exactly are you trying to do and what is the behaviour you expect?

**Comment by imle** [comment]
Sorry for not getting back to you @jeremypoulter 

The issue appears to be with OCPP in Home Assistant:
https://github.com/lbbrhzn/ocpp/issues/844

**Comment by imle** [comment]
I will note this seems to be an issue because OpenEVSE does not support `ChargingScheduleAllowedChargingRateUnit`

**Comment by matth-x** [comment]
@imle There is a good chance that this issue will be resolved with the newest OCPP update of OpenEVSE, because the `ChargingScheduleAllowedChargingRateUnit` config is supported there. If you like to give it a try, that would be great. I would be very interested if it helps here. You can find the update here: https://github.com/matth-x/ESP32_WiFi_V4.x

**Comment by imle** [comment]
Thanks for the info, I will see if I can get it to work! However, I did manage to work around it through some edits to the OCPP home assistant integration.

**Comment by matth-x** [comment]
Thanks!

I'm curious: what did you need to change in the HASS integration?
